services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    hostname: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Casablanca
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - plex-config:/config
      - /media:/media
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

volumes:
  plex-config:

