services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    hostname: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Casablanca
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - deluge-config:/config
      - /media:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped

volumes:
  deluge-config:

